In [1]:
import numpy as np
from task3 import ldm_decomposition

In [2]:
def is_positive_definite(A):
    _, D, _ = ldm_decomposition(A)
    return np.all(np.diag(D) > 0)

In [8]:
# Пример
A = np.array([[4, 2, 2],
              [2, 10, 4],
              [2, 4, 6]], dtype=float)

L, D, M = ldm_decomposition(A)

print("L:")
print(L)
print("D:")
print(D)
print("M:")
print(M)
print("||LDM^T - A||2:")
print(np.linalg.norm(L @ D @ M.T - A, 1))
print("Положительно определённая? ", is_positive_definite(A))

L:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
D:
[[4. 0. 0.]
 [0. 9. 0.]
 [0. 0. 4.]]
M:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
||LDM^T - A||2:
0.0
Положительно определённая?  True
