In [1]:
import numpy as np
from task2 import inverse_matrix

In [2]:
# Пример использования
A = np.array([[3, 1, -1], [2, 4, 1], [1, -1, 2]], dtype=float)
A_inv = inverse_matrix(A)
verification = np.dot(A, A_inv)

print("Найденная обратная матрица A^(-1):")
print(A_inv)
print("Проверка A * A^(-1):")
print(verification)

Найденная обратная матрица A^(-1):
[[ 0.3        -0.03333333  0.16666667]
 [-0.1         0.23333333 -0.16666667]
 [-0.2         0.13333333  0.33333333]]
Проверка A * A^(-1):
[[ 1.00000000e+00  0.00000000e+00  5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00  1.11022302e-16]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00]]
